fix: missing params in message
vfurmane/ft_irc pull request #156
Opened 2022-10-21 16:33 UTC by theovgl

2022-10-21 16:41 UTC, ppiques requested changes
LGTM, sorry for the review but I think we can squeeze this change in this PR

2022-10-21 16:41 UTC, ppiques commented on include/IRCErrors.hpp
> +		ERR_NICKNAMEINUSE(const std::string &author_nick, const std::string &nick) : _str("433 * " + author_nick + " " + nick + " :Nickname is already in use") {}
should remove the '*'
(433 ppiques ppiques_ :Nickname is already in use.)

2022-10-21 16:50 UTC, ppiques approved these changes

2022-10-21 17:16 UTC, vfurmane approved these changes

2022-10-21 17:17 UTC, vfurmane requested changes
Did not mean to approve last one

2022-10-21 17:23 UTC, vfurmane approved these changes

2022-10-21 17:30 UTC, ppiques approved these changes

2022-10-22 07:28 UTC, vfurmane approved these changes

2022-10-22 07:28 UTC, merged