Join messages
vfurmane/ft_irc pull request #16
Opened 2022-09-19 16:02 UTC by vfurmane

2022-09-20 07:55 UTC, ppiques approved these changes
TL; still DR

2022-09-20 10:12 UTC, theovgl requested changes

2022-09-20 10:12 UTC, theovgl commented on include/IRCPeerManager.hpp
> +};
Wrong class name :(

2022-09-20 10:12 UTC, theovgl commented on src/IRCPeerManager.cpp
> +}
Wrong class name again

2022-09-20 13:10 UTC, ppiques approved these changes
style

2022-09-20 13:11 UTC, ppiques approved these changes

2022-09-20 14:24 UTC, theovgl approved these changes

2022-09-21 08:17 UTC, ppiques approved these changes

2022-09-21 13:07 UTC, merged