feat: add quit command
vfurmane/ft_irc pull request #21
Opened 2022-09-23 10:00 UTC by theovgl

2022-09-23 10:28 UTC, vfurmane requested changes

2022-09-23 10:28 UTC, vfurmane commented on include/commands.hpp
> +struct QuitMessage : public IRCMessage
Should be called `ErrorMessage` instead of `QuitMessage`

2022-09-23 10:28 UTC, vfurmane commented on src/commands.cpp
> +QuitMessage::ErrorMessage(IRCPeer &peer, const std::string &quit_message)
Should be called `ErrorMessage` instead of `QuitMessage`

2022-09-23 10:28 UTC, vfurmane commented on src/commands/quit.cpp
> +	message.peer.sendMessage(ErrorMessage(message.peer, message.getArguments()[]));
No index inside the `[]` operator

2022-09-23 11:26 UTC, ppiques approved these changes

2022-09-26 11:54 UTC, vfurmane approved these changes
What a surprise

2022-09-26 11:54 UTC, merged