feat: add user command
vfurmane/ft_irc pull request #23
Opened 2022-09-23 11:48 UTC by ppiques

2022-09-23 15:10 UTC, vfurmane requested changes
![meme so funny to descendre ppik gratuitement](https://survivrelanuit.files.wordpress.com/2015/10/dewey.gif)

2022-09-23 15:10 UTC, vfurmane commented on include/IRCPeer.hpp
> +class IRCMessage;
Useless definition

2022-09-23 15:10 UTC, vfurmane commented on src/commands/user.cpp
> +	int mode = stoi(message.getArguments[1], &pos, 10);
Nice try but it is C++11

2022-09-26 10:07 UTC, theovgl requested changes

2022-09-26 10:07 UTC, theovgl commented on test/TCP/Server.test.cpp
> +#include "TCP/Server.hpp"
Hop ca saute

2022-09-26 11:36 UTC, theovgl approved these changes

2022-09-26 11:56 UTC, vfurmane approved these changes

2022-09-26 11:57 UTC, merged