fix: check if we are sent 512 characters or more
vfurmane/ft_irc pull request #28
Opened 2022-09-29 14:40 UTC by ppiques

2022-09-29 16:54 UTC, theovgl commented
> huge pr take your time to check all files and read it all

ahahah menteur

2022-09-29 16:54 UTC, theovgl approved these changes
Mais du coup on le fait quand meme ? Juzain et tout avait pas de limite non ?

2022-09-30 07:46 UTC, vfurmane requested changes

2022-09-30 07:46 UTC, vfurmane commented on src/Server.cpp
> +		}
A debug message would be nice

2022-09-30 07:46 UTC, vfurmane commented on src/Server.cpp
> +		if (peer.getMessage().length() + bytes_read > 512)
The 512 characters limit could be a define (yes a define, not a static const)

2022-09-30 09:39 UTC, vfurmane approved these changes

2022-09-30 09:41 UTC, merged