feat: add extra parsing for user command and tests
vfurmane/ft_irc pull request #29
Opened 2022-09-29 14:55 UTC by ppiques

2022-09-29 16:42 UTC, theovgl approved these changes

2022-09-30 07:52 UTC, vfurmane requested changes

2022-09-30 07:52 UTC, vfurmane commented on src/commands/user.cpp
> +	if	(forbidden_user_char(message.arguments[0]) == true)
Should be a space after the `if`

2022-09-30 07:52 UTC, vfurmane commented on src/commands/user.cpp
> +	std::string forbidden = "@\r\n ";
This variable shoud be const

2022-09-30 09:48 UTC, vfurmane approved these changes

2022-09-30 09:53 UTC, merged