feat: check if the nickname is used in NICK command
vfurmane/ft_irc pull request #31
Opened 2022-09-29 16:16 UTC by vfurmane

2022-09-29 16:52 UTC, theovgl approved these changes
Ca me semble bon, mais du coup je pense qu'il va falloir merge cette branch avant la #32. Ou en fait l'inverse mais en fait on a tout les deux fait getUsername de notre cote. Voila rien de grave :)

2022-09-30 07:49 UTC, ppiques requested changes
c'est bien mais il faut check si le meme nickname existe pas en majuscule ou minuscule

2022-09-30 09:47 UTC, ppiques requested changes
needs a few small changes to make it a bit easier to read, but otherwise it looks good

2022-09-30 09:47 UTC, ppiques commented on src/commands/nick.cpp
> +	throw ERR_NICKNAMEINUSE(message.arguments[0]);
it's not very clear. redo it but better

2022-09-30 09:56 UTC, ppiques approved these changes
you are the boss @vfurmane

2022-09-30 09:56 UTC, merged