feat: Implement prefix
vfurmane/ft_irc pull request #32
Opened 2022-09-29 16:43 UTC by theovgl

2022-09-29 16:45 UTC, theovgl commented
Ok, je dois corriger les tests en fait ca marche qu'en local ce que j'ai fait

2022-09-29 18:21 UTC, valfur03 requested changes

2022-09-29 18:21 UTC, valfur03 commented on src/Message.cpp
> +		this->prefix = new std::string;
Possible memory leaks if old prefix is not deleted

2022-09-29 18:21 UTC, valfur03 commented on src/Message.cpp
> +}
I think the function should call the `updateInputFromFields` method

2022-09-29 18:21 UTC, valfur03 commented on src/Peer.cpp
> +#include <memory>
Misplaced include (should be in the header file)

2022-09-29 18:21 UTC, valfur03 commented on test/Message.test.cpp
> +	}
The `struct sockaddr` fields should be set as they are really being used (e.g. the IP field)

2022-09-30 07:53 UTC, ppiques reviewed
LGTM besides what @valfur03 underlined

2022-09-30 11:52 UTC, closed without merging