feat: add the following classes needed for channel implementation : Channel, User, UserManager
vfurmane/ft_irc pull request #40
Opened 2022-10-03 15:45 UTC by ppiques

The classes are not meant to be used as is but to be a base for further implementation.

2022-10-03 15:52 UTC, theovgl requested changes

2022-10-03 15:52 UTC, theovgl commented on include/UserManager.hpp
> +
Maybe you can add some accessors like `begin()` or `end()` :)

2022-10-03 15:52 UTC, theovgl commented on include/UserManager.hpp
> +
And overload the operator []

2022-10-03 15:52 UTC, theovgl commented on include/User.hpp
> +
You can add the `getName()` method, it may be useful later

2022-10-03 16:10 UTC, theovgl approved these changes

2022-10-04 08:35 UTC, vfurmane requested changes

2022-10-04 08:35 UTC, vfurmane commented on include/User.hpp
> +#include <string>
![image](https://user-images.githubusercontent.com/76964081/193772534-9d4cbb6c-c6b1-4d4e-8530-b6e7752bf93b.png)

2022-10-04 08:35 UTC, vfurmane commented on include/UserManager.hpp
> +#include "User.hpp"
![image](https://user-images.githubusercontent.com/76964081/193772714-2169e282-36c2-4f54-895b-c41262f5e201.png)

2022-10-04 08:35 UTC, vfurmane commented on include/User.hpp
> +		std::string	_name;
The `User` class should have a reference to a Peer and the name would be stored in it. It prevents duplication of code.

2022-10-04 09:14 UTC, vfurmane requested changes

2022-10-04 09:14 UTC, vfurmane commented on include/Channel.hpp
> +# include <stdint.h>
Plouto do foi koune

2022-10-04 12:57 UTC, vfurmane approved these changes
Could be better....

2022-10-04 12:58 UTC, theovgl approved these changes

2022-10-04 12:59 UTC, merged