Irssi
vfurmane/ft_irc pull request #90
Opened 2022-10-13 15:02 UTC by vfurmane

2022-10-13 15:02 UTC, vfurmane commented
Merge after #89

2022-10-13 15:43 UTC, ppiques requested changes

2022-10-13 15:43 UTC, ppiques commented on include/commands.hpp
> +
extra newline

2022-10-13 15:55 UTC, theovgl requested changes

2022-10-13 15:55 UTC, theovgl commented on include/commands.hpp
> +
???

2022-10-14 15:22 UTC, theovgl approved these changes

2022-10-16 08:44 UTC, ppiques approved these changes
gpalu

2022-10-16 08:45 UTC, merged